Servidor/config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :proposals

  get 'users/new'

  get 'users/edit'

  resources :subjects

  resources :scopes

  resources :propuesta

  root 'proposals#index'

  get 'creador' => 'proposals#creador'
  get 'votator' => 'votes#votator'
  get 'counter' => 'votes#counter'

end

Servidor/app/models/proposal.rb
class Proposal < ActiveRecord::Base
    belongs_to :scope
    belongs_to :subject
    has_many :votes
end

Servidor/app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def creador
    @proposal = Proposal.create(:title => params[:title], :user_id => 1, :object => params[:object], :finality => params[:finality], :subject_id => params[:subject_id], :scope_id => params[:scope_id])
    render :json => @proposal
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:user_id, :title, :object, :finality, :scope_id, :subject_id)
    end
end

Servidor/app/helpers/proposals_helper.rb
module ProposalsHelper
end

Servidor/app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :object %><br>
    <%= f.text_field :object %>
  </div>
  <div class="field">
    <%= f.label :finality %><br>
    <%= f.text_field :finality %>
  </div>
  <div class="field">
    <%= select("proposal","scope_id", Scope.all.collect {|p| [ p.name, p.id ] }, {include_blank: true})%>    
  </div>
  <div class="field">
    <%= select("proposal","subject_id", Subject.all.collect {|p| [ p.name, p.id ] }, {include_blank: true})%> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Servidor/app/views/proposals/edit.html.erb
<h1>Edici&oacute;n de propuestas</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @proposal %> |
<%= link_to 'Volver', proposals_path %>

Servidor/app/views/proposals/index.html.erb
<h1>Lista de propuestas</h1>
<div class="col-lg-12">
<table class="table table-hover">
  
    <tr>
      <th>Usuario</th>
      <th>T&iacute;tulo</th>
      <th>Objetivo</th>
      <th>Finalidad</th>
      <th>&Aacute;mbito</th>
      <th>Tem&aacute;tica</th>
      <th colspan="3"></th>
    </tr>
 

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.user_id %></td>
        <td><%= proposal.title %></td>
        <td><%= proposal.object %></td>
        <td><%= proposal.finality %></td>
        <td><%= proposal.scope.name %></td>
        <td><%= proposal.subject.name %></td>
        <td ><%=  link_to 'Mostrar', proposal, :class => "btn btn-default"  %></td>
        <td><%= link_to 'Editar', edit_proposal_path(proposal) %></td>
        <td><%= link_to 'Eliminar', proposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Nueva propuesta', new_proposal_path %>

Servidor/app/views/proposals/new.html.erb
<h1>Nueva propuesta</h1>

<%= render 'form' %>

<%= link_to 'Volver', proposals_path %>

Servidor/app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @proposal.user_id %>
</p>

<p>
  <strong>T&iacute;tulo:</strong>
  <%= @proposal.title %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @proposal.object %>
</p>

<p>
  <strong>Finalidad:</strong>
  <%= @proposal.finality %>
</p>

<p>
  <strong>&Aacute;mbito:</strong>
  <%= @proposal.scope.name %>
</p>

<p>
  <strong>Tem&aacute;tica:</strong>
  <%= @proposal.subject.name %>
</p>

<%= link_to 'Editar', edit_proposal_path(@proposal) %> |
<%= link_to 'Volver', proposals_path %>