Servidor/config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :proposals

  get 'users/new'

  get 'users/edit'

  resources :subjects

  resources :scopes

  resources :propuesta

  root 'proposals#index'

  get 'creador' => 'proposals#creador'
  get 'votator' => 'votes#votator'
  get 'counter' => 'votes#counter'

end

Servidor/app/models/scope.rb
class Scope < ActiveRecord::Base
    has_many :proposals
end

Servidor/app/controllers/scopes_controller.rb
class ScopesController < ApplicationController
  before_action :set_scope, only: [:show, :edit, :update, :destroy]

  # GET /scopes
  # GET /scopes.json
  def index
    @scopes = Scope.all
  end

  # GET /scopes/1
  # GET /scopes/1.json
  def show
  end

  # GET /scopes/new
  def new
    @scope = Scope.new
  end

  # GET /scopes/1/edit
  def edit
  end

  # POST /scopes
  # POST /scopes.json
  def create
    @scope = Scope.new(scope_params)

    respond_to do |format|
      if @scope.save
        format.html { redirect_to @scope, notice: 'Scope was successfully created.' }
        format.json { render :show, status: :created, location: @scope }
      else
        format.html { render :new }
        format.json { render json: @scope.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scopes/1
  # PATCH/PUT /scopes/1.json
  def update
    respond_to do |format|
      if @scope.update(scope_params)
        format.html { redirect_to @scope, notice: 'Scope was successfully updated.' }
        format.json { render :show, status: :ok, location: @scope }
      else
        format.html { render :edit }
        format.json { render json: @scope.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scopes/1
  # DELETE /scopes/1.json
  def destroy
    @scope.destroy
    respond_to do |format|
      format.html { redirect_to scopes_url, notice: 'Scope was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scope
      @scope = Scope.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scope_params
      params.require(:scope).permit(:name)
    end
end

Servidor/app/helpers/scopes_helper.rb
module ScopesHelper
end

Servidor/app/views/scopes/_form.html.erb
<%= form_for(@scope) do |f| %>
  <% if @scope.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scope.errors.count, "error") %> prohibited this scope from being saved:</h2>

      <ul>
      <% @scope.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Servidor/app/views/scopes/edit.html.erb
<h1>Edici&oacute;n &Aacute;mbito</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @scope %> |
<%= link_to 'Volver', scopes_path %>

Servidor/app/views/scopes/index.html.erb
<h1>Lista de los &Aacute;mbitos</h1>
<div class="col-lg-12">
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scopes.each do |scope| %>
      <tr>
        <td><%= scope.name %></td>
        <td><%= link_to 'Mostrar', scope %></td>
        <td><%= link_to 'Editar', edit_scope_path(scope) %></td>
        <td><%= link_to 'Eliminar', scope, method: :delete, data: { confirm: '¿Est&aacute;s seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Scope', new_scope_path %>

Servidor/app/views/scopes/new.html.erb
<h1>Nuevo &Aacute;mbito</h1>

<%= render 'form' %>

<%= link_to 'Volver', scopes_path %>

Servidor/app/views/scopes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @scope.name %>
</p>

<%= link_to 'Editar', edit_scope_path(@scope) %> |
<%= link_to 'Volver', scopes_path %>