Servidor/config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :proposals

  get 'users/new'

  get 'users/edit'

  resources :subjects

  resources :scopes

  resources :propuesta

  root 'proposals#index'

  get 'creador' => 'proposals#creador'
  get 'votator' => 'votes#votator'
  get 'counter' => 'votes#counter'

end

Servidor/app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :proposal
end

Servidor/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'El voto se cre&oacute; satisfactoriamente.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def votator
    @vote = Vote.create(:proposal_id => params[:proposal_id], :vote => params[:vote])
    render :json => @vote
  end
  
  def counter
    @total = 0;
    @votes = Vote.where(:proposal_id => params[:proposal_id])
    @votes.each do |v|
      @total= @total + v.vote
    end
    render :json => @total
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'El voto se actualiz&oacute; satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'El voto se elimin&oacute; satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:proposal_id, :vote)
    end
end

Servidor/app/helpers/votes_helper.rb
module VotesHelper
end

Servidor/app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proposal_id %><br>
    <%= f.text_field :proposal_id %>
  </div>
  <div class="field">
    <%= f.label :vote %><br>
    <%= f.text_field :vote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Servidor/app/views/votes/edit.html.erb
<h1>Edici&oacute;n de votos</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @vote %> |
<%= link_to 'Volver', votes_path %>

Servidor/app/views/votes/index.html.erb
<h1>Lista de votos</h1>

<table>
  <thead>
    <tr>
      <th>Propuesta</th>
      <th>Voto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.proposal_id %></td>
        <td><%= vote.vote %></td>
        <td><%= link_to 'Mostrar', vote %></td>
        <td><%= link_to 'Editar', edit_vote_path(vote) %></td>
        <td><%= link_to 'Eliminar', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo voto', new_vote_path %>

Servidor/app/views/votes/new.html.erb
<h1>Nuevo voto</h1>

<%= render 'form' %>

<%= link_to 'Volver', votes_path %>

Servidor/app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Propuesta: </strong>
  <%= @vote.proposal_id %>
</p>

<p>
  <strong>Voto: </strong>
  <%= @vote.vote %>
</p>

<%= link_to 'Editar', edit_vote_path(@vote) %> |
<%= link_to 'Volver', votes_path %>